In [4]:
 import numpy as np
 # Q1
 arr = np.array([1,2,3,4,5])
 print("Original Array: ",arr)
 print("Array after addition of 2: ",arr+2)
 print("Array after multiplication by 3: ",arr*3)
 print("Array after dividing by 2: ",arr/2)

Original Array:  [1 2 3 4 5]
Array after addition of 2:  [3 4 5 6 7]
Array after multiplication by 3:  [ 3  6  9 12 15]
Array after dividing by 2:  [0.5 1.  1.5 2.  2.5]


In [5]:
# Q2 (a)
arr1 = np.array([1, 2, 3, 6, 4, 5])
reverse = arr1[::-1]
print("Reversed Array: ",reverse)

Reversed Array:  [5 4 6 3 2 1]


In [14]:
# Q2 (b)(i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_freq_x = values[np.argmax(counts)]
indices_x = np.where(x == most_freq_x)[0]
print("Most frequent value in x:", most_freq_x)
print("Indices in x:", indices_x)

1
Most frequent value in x: 1
Indices in x: [0 5 7 8 9]


In [15]:
# Q2 (b)(ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values, counts = np.unique(y, return_counts=True)
most_freq_y = values[np.argmax(counts)]
indices_y = np.where(y == most_freq_y)[0]
print("Most frequent value in y:", most_freq_y)
print("Indices in y:", indices_y)

Most frequent value in y: 1
Indices in y: [0 1 2]


In [19]:
# Q3
arr3=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at (1, 2):",arr3[0][1])
print("Element at (3, 1):",arr3[2][0])

Element at (1, 2): 20
Element at (3, 1): 70


In [24]:
# Q4
Pulkit = np.linspace(10,100,25)
print("Array:", Pulkit)
print("Shape:", Pulkit.shape)
print("Total Elements:", Pulkit.size)
print("Data Type:", Pulkit.dtype)
print("Total Bytes:", Pulkit.nbytes)

reshape = Pulkit.reshape(25, 1)
print("Transposed Array using reshape:\n", reshape)

transpose = Pulkit.T
print("Transposed Array using transpose:\n",transpose)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Transposed Array using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed Array using transpose:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [28]:
# Q5
ucs420_Pulkit = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])

print('Mean',np.mean(ucs420_Pulkit))
print('Median',np.median(ucs420_Pulkit))
print('Max Element',np.max(ucs420_Pulkit))
print('Min Element',np.min(ucs420_Pulkit))
print('Unque Elemnts',np.unique(ucs420_Pulkit))

reshaped_ucs420_Pulkit = ucs420_Pulkit.reshape(4, 3)
print('Reshaped Array:\n', reshaped_ucs420_Pulkit)

resized_ucs420_Pulkit = np.resize(ucs420_Pulkit, (2, 3))
print('Resized Array:\n', resized_ucs420_Pulkit)

Mean 43.333333333333336
Median 37.5
Max Element 90
Min Element 10
Unque Elemnts [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [40 50 60]]
